---
- hosts: all
  become: yes
  tasks:
    - name: Full system upgrade
      become: yes
      apt:
        update_cache: yes
        upgrade: yes
    - name: Install CLI apps and libraries
      apt:
        name:
          - build-essential
          - software-properties-common
          - git
          - make
          - htop
          - iotop
          - rsync
        state: latest
    - name: Install nodejs
      apt:
        name:
          - nodejs
          - node-gyp
          - npm
        state: latest
